services:
  mlflow:
    image: python:3.9-slim
    container_name: mlflow-server
    restart: always
    ports:
      - "${MLFLOW_PORT:-5000}:5000"
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-north-1}
      - MLFLOW_HOST=0.0.0.0
    volumes:
      - ${MLFLOW_DATA_DIR:-./mlflow_data}:/opt/mlflow
    working_dir: /opt/mlflow
    command: |
      bash -c "
        pip install mlflow[extras] boto3 psutil &&
        export MLFLOW_HOST=0.0.0.0 && \
        mlflow server \
          --backend-store-uri ${MLFLOW_BACKEND_STORE_URI:-sqlite:////opt/mlflow/mlruns.db} \
          --default-artifact-root ${MLFLOW_ARTIFACT_ROOT:-s3://ai-drug-artifacts/} \
          --host 0.0.0.0 \
          --port 5000 \
          --gunicorn-opts '--bind 0.0.0.0:5000'
      "
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000')"]
      interval: 5s
      timeout: 3s
      retries: 12
    networks:
      - default

  training:
    image: ${TRAINING_IMAGE:-ghcr.io/j0mt/ai-drug-training:latest}
    depends_on:
      mlflow:
        condition: service_healthy
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-north-1}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - RUN_MODE=${RUN_MODE:-prod}
    command: ["python", "train_dispatch_pure.py"]
    profiles: ["training"]

networks:
  default:
    driver: bridge