n_estimators: 2
max_depth: 6
learning_rate: 0.1
subsample: 0.8
colsample_bytree: 0.8
random_state: 42

model_type: xgb
model_path: models/xgb
model_file: train.py
model_script: models/xgb/train.py
model_source: models/xgb/model.py
config_path: configs/xgb.yaml
signature_files:
  - models/xgb/model.py
  - models/xgb/train.py