name: Test, Lint, and Smoke-Train Models

on: [push, pull_request]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1


      - name: Run black (check only)
        run: black . --check

      - name: Run flake8 linter
        run: flake8 .

      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest tests/

      - name: Run dry-run for all models
        run: |
          for d in models/*; do
            if [ -f "$d/train.py" ]; then
              echo "Dry-running $d/train.py"
              PYTHONPATH=. python -m $(echo $d | sed 's/\//./g').train --dry-run
            fi
          done
